version: '3.3'

services:
  labelstudio:
    image: heartexlabs/label-studio:1.11.0 # https://hub.docker.com/r/heartexlabs/label-studio
    container_name: labelstudio
    ports:
      - "8080:8080"
    volumes:
      - ../data/labelstudio-data:/label-studio/data # inner data for LS
      - ../data/yolo_datasets:/label-studio/mydata # my custom files that label studio has access to
    user: "1001"
    environment:
      - LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true
      - LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=/label-studio/mydata